sdaqo/anipy-cli

requirements.txt, src/url.py
Hi,
I'm pretty new to python and this kind of coding, but here is example of what we talked about in issue #3 
Here is webdriver manager: https://github.com/SergeyPirogov/webdriver_manager
You could let people choose to run the browser of their choosing with this.
Maybe this is helpful, maybe not, this is my first contribution lol :)
=> Switch to webdriver manager?

README.md, makefile, src/url.py
Hi again,
I'm not sure if you want to implement something like this, but this makes it possible to use chrome and chromium for webdrivers.
What do you think?
Tested on Linux and Windows, as i have no mac there is no implementation for it, so it defaults to Firefox.
Daniel
=> More browser compatibility

main.py, src/history.py
These commits use `pathlib.Path` in order to store and use paths better. They also makes sure that all files that are opened are closed properly and they remove some now unnecessary imports.
=> Utilize pathlib

config.py, main.py, src/download.py, src/history.py, src/menu.py, src/play.py, src/query.py, src/url.py
This pull request has quite a lot of changes in it.
1. I extracted all of the paths in the program to config.py for easy editing
2. I extracted the gogoanime url to config.py so it can easily be changed if needed
3. I extracted the path to mpv and allowed for adding extra arguments to mpv 
4. Formatted all of the .py files with yapf
=> Create a config.py file that stores some constant values

main.py, src/download.py, src/history.py, src/menu.py, src/play.py, src/query.py
This pull request fixes the issue found in issue #14 about not being able to download anime with the -d flag.
=> Change the method used to import config.py into files in src/

.gitignore, config.py, src/history.py
These commit improve the documentation on the `pathlib.Path` object in `config.py` file and also remove the requirement to make a history folder.
=> Improve config and remove history folder requierment 

main.py, src/binge.py, src/menu.py, src/url.py
Heya!
Had some free time so i coded `binge mode`. This takes in multiple episodes and queues them while the first video is playing.
Every time the player closes the next video will be played.
The download mode code was really helpful here!
The inspiration is taken from feature request for ani-cli, this is good way to differentiate us: https://github.com/pystardust/ani-cli/issues/102
Is this something we want to implement? if so, please test this before merging :smile: 
Daniel
=> Binge mode

anipy_cli/url_handler.py
Heya
This seem to work, had to replace some part of string and have no idea why it came out with quotes and a `b` after encrypting.
Can look into refactoring later!
Test if everything works on your end :+1:
=> Get urls without dependencies

README.md
When I first created these sections, they looked bad. Now, I fixed them so they actually display as lists, not strange-looking blobs of text.
=> Fix the Pros and Cons sections of the readme for the linux install section

anipy_cli/anime_info.py, anipy_cli/cli.py, requirements.txt, setup.py
This should fix the issue with not having the newest version of kitsu.py in pypi
=> Switched from kitsu.py to kitsu.py-extended

anipy_cli/seasonal.py
Seasonals start at EP2.
```
Stuff to be downloaded:
Kaguya-sama wa Kokurasetai: Ultra Romantic:
==> EP: 2
Komi-san wa, Comyushou desu. 2nd Season:
==> EP: 2
Gotoubun no Hanayome:
==> EP: 2
==> EP: 3
==> EP: 4
==> EP: 5
```
```
Stuff to be downloaded:
Kaguya-sama wa Kokurasetai: Ultra Romantic:
==> EP: 1
==> EP: 2
Komi-san wa, Comyushou desu. 2nd Season:
==> EP: 1
==> EP: 2
...
```
=> Bugfix Seasonals start at EP2

anipy_cli/config.py, anipy_cli/download.py, setup.py
This just lets people configure what they want the name of the episodes downloaded to be.
=> Allow for the customization of downloaded file names

anipy_cli/misc.py, anipy_cli/url_handler.py
Title says what I fixed. It seems that some formatting has also been fixed with black
=> entry.latest_ep should always be an int or float. it was a str

anipy_cli/config.py, requirements.txt, setup.py
There were a few issues, so I fixed them
=> Fixes for new conf system

anipy_cli/misc.py
Fixed a bug where a keyboard interrupts which exists the program, changes terminal color to error color
Also some typos
=> fixed color bug on keyboard interrupt & some typos

anipy_cli/arg_parser.py, anipy_cli/cli.py, anipy_cli/colors.py, anipy_cli/config.py, anipy_cli/download.py, anipy_cli/misc.py, anipy_cli/player.py, anipy_cli/query.py, anipy_cli/url_handler.py, docs/anipycli_as_lib.py, docs/sample_config.yaml, setup.py, tests/config/test_config.py, tests/download/test_download.py, tests/episode_handling/test_ep_handler.py, tests/history/test_history.py, tests/query/test_query.py, tests/seasonal/test_seasonal.py, tests/stream/test_stream.py
Better handling of coloring text and input.
- Created 3 functions: one for coloring text, one for printing text and one for colored input.
- Replaced the appropriate places in the code with the new functions.
- Fixed some typos.
=> Color func

anipy_cli/cli.py, anipy_cli/config.py, anipy_cli/mal.py, docs/sample_config.yaml
A couple of small fixes.
bugfixes:
- Fixed a bug in config.py where catching a PermissionError in creating config file didn't display the error message
- fixed a bug in adding anime through mal cli where selecting anime chose the next anime on the list instead
modifications:
- Added mal credentials to sample config
- changed the limit in 'MAL.get_anime'  from 3 to 10. 3 is way too little, and the chance of not getting what you want is high. Possibly this should be more than 10
- a bit of code cleanup
=> A couple of small fixes

README.md, anipy_cli/arg_parser.py, anipy_cli/cli.py, anipy_cli/mal.py, anipy_cli/misc.py, setup.py
- improved auto-mapping performance by using multiprocessing
- implemented #113 
- small fixes in outputs
=> Improvements

anipy_cli/cli/menus/menu.py, anipy_cli/cli/menus/seasonal_menu.py, anipy_cli/cli/util.py, anipy_cli/colors.py, anipy_cli/download.py, anipy_cli/mal.py, anipy_cli/player/player.py, anipy_cli/query.py, anipy_cli/seasonal.py, anipy_cli/url_handler.py, setup.py
Added some loading CLIspinners (it sometimes takes a while to load animes, especially in seasonal mode) so now its a bit better.
That, and a few tweaks mostly just adding the clear_console method at some places where it helps the terminal look less like a spaghetti).
--- Added dependency: **yaspin**
=> Minor Visual Tweaks 0.1 (Loading spinner)

anipy_cli/config.py
old link is blocked in my region + old link only ever redirects to new website anyway
=> change link to new website

cli/src/anipy_cli/config.py
Rephrased the sentence to make it clearer (immediately eliminating the typo too)
=> Provider configurations comment updated

api/src/anipy_api/provider/providers/anivibe_provider.py
For sometimes Anivide default Vidplay stream is not working so i switch to other streams.
Add support for multi stream provider like Vidhide and Streamwish 
I have a question is there any api to specify multi stream provider in anivide but default for now it set for Vidhide but Streamwish also works for some anime.
I am new to this codebase if any mistake you can point out to me or suggest me another method.
=> fix default anivide stream provider

api/src/anipy_api/download.py, api/src/anipy_api/player/base.py, api/src/anipy_api/provider/providers/animekai_provider.py, cli/src/anipy_cli/arg_parser.py, cli/src/anipy_cli/clis/download_cli.py, cli/src/anipy_cli/download_component.py
=> fix decoding of sub and wrong names for some and add sub-only download option

api/src/anipy_api/download.py, api/src/anipy_api/player/base.py, api/src/anipy_api/player/players/mpv_control.py, api/src/anipy_api/provider/base.py, api/src/anipy_api/provider/providers/allanime_provider.py, api/src/anipy_api/provider/providers/animekai_provider.py, api/src/anipy_api/provider/utils.py, cli/poetry.lock, cli/src/anipy_cli/clis/download_cli.py, cli/src/anipy_cli/config.py, cli/src/anipy_cli/download_component.py, cli/src/anipy_cli/menus/menu.py, cli/src/anipy_cli/menus/seasonal_menu.py, cli/src/anipy_cli/prompts.py, cli/src/anipy_cli/util.py
Turns out the errors on #263 were caused by possibly the MP4 download function not being tested (totally fair lol). After testing on my side, I was able to fix the bugs and optimize a bit. 
Ran polish and fixed a ruff error too :).
=> Fix MP4 Download Errors
